### ISSUE TITLE
SphinxDoctest is not sortable

### ISSUE THREAD

**Issue by rmorshea** [thisch/pytest-sphinx#1]
Pytest now runs `tests.sort()` which results in an error complaining that:

```
TypeError: '<' not supported between instances of 'SphinxDoctest' and 'SphinxDoctest'
```

Adding the following comparisons to the `SphinxDoctest` class may resolve this issue:

Operator | Method
-- | --
`==` | `__eq__`
`!=` | `__ne__`
`<` | `__lt__`
`<=` | `__le__`
`>` | `__gt__`
`>=` | `__ge__`

**Comment by thisch** [comment]
Thx for using pytest-sphinx and creating the first issue on the github package!

I've grepped for "tests.sort()" in the pytest repo (master branch) and I haven't found any matches. Could it be that a pytest plugin you are using is calling tests.sort()?

**Comment by thisch** [comment]
kindly ping

**Comment by rmorshea** [comment]
@thisch I keep coming back to this issue when I don't have access to my work computer. I'll make a not to address this tomorrow. That said, you're probable right - there's likely a plugin that's causing this.

**Comment by KostyaEsmukov** [comment]
Facing the same issue with cpython 3.7. 

Stacktrace: 
```
../../../.virtualenvs/geopy/lib/python3.7/site-packages/pytest_sphinx.py:368: in collect
    for test in finder.find(module, module.__name__):
../../../.pyenv/versions/3.7.0/lib/python3.7/doctest.py:937: in find
    tests.sort()
E   TypeError: '<' not supported between instances of 'SphinxDoctest' and 'SphinxDoctest'
```
The `tests.sort()` reference in the doctest module: https://github.com/python/cpython/blob/d5fbe9b1a3d65ceeb9159c5ba999ee966a945f76/Lib/doctest.py#L937

The comparison operator defined in `DocTest` (which instances are being sorted): https://github.com/python/cpython/blob/d5fbe9b1a3d65ceeb9159c5ba999ee966a945f76/Lib/doctest.py#L561-L566

BTW, is there a reason to introduce `SphinxDoctest` instead of just using the `doctest.DocTest`?
