### ISSUE TITLE
flake8: Additional rules

### ISSUE THREAD

**Issue by tony** [thisch/pytest-sphinx#52]
@thisch Discovered these through [sphinx](https://github.com/sphinx-doc/sphinx/blob/afac558/setup.py#L43-L44), thoughts?

flake8-bugbear: https://github.com/PyCQA/flake8-bugbear
flake8-comprehensions: https://github.com/adamchainz/flake8-comprehensions

PR: #47

**Comment by thisch** [comment]
I'm not sure if I would add more and more tools to the development/CI setup of `pytest-sphinx`. I think the basic tools (mypy, flake8/pylint, black) are fine. Since you've recently discovered those tools, I guess that you are so far not using them in your projects, right?

I also think that the benefit for `pytest-sphinx` of the mentioned flake8 tools/plugins is only very minor.

**Comment by tony** [comment]
This is acceptable to me. There isn't much picked up by these rules.

I have rolled them out on my own projects (not much cost in doing so) - there was only a single rule I found while checking pytest-sphinx, so maybe not worth it 🤷
